/**
 * Sample cryptography, cryptology, and cryptanalysis events
 * for testing and development purposes
 */

const sampleCryptoEvents = [
    {
      id: 1,
      title: "International Cryptography Conference 2024",
      description: "Join leading cryptographers from around the world for presentations on the latest advances in cryptographic research, including post-quantum cryptography, zero-knowledge proofs, and secure multi-party computation techniques.",
      startDate: "2024-07-15T09:00:00Z",
      endDate: "2024-07-18T17:00:00Z",
      location: "Zurich, Switzerland",
      imageUrl: "https://images.unsplash.com/photo-1526378800651-c1a408aaf68b",
      category: "conference",
      source: "college",
      organizerName: "International Association for Cryptologic Research",
      organizerImageUrl: "",
      registrationUrl: "https://example.com/crypto-conference-2024",
      isFeatured: true,
      approved: true
    },
    {
      id: 2,
      title: "Workshop on Cryptographic Hardware Security",
      description: "A hands-on workshop focusing on hardware security modules, side-channel attacks, and implementation vulnerabilities in cryptographic systems. Participants will learn practical techniques for securing cryptographic hardware.",
      startDate: "2024-09-10T10:00:00Z",
      endDate: "2024-09-11T16:00:00Z",
      location: "Berlin, Germany",
      imageUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31",
      category: "workshop",
      source: "college",
      organizerName: "Technical University of Berlin",
      organizerImageUrl: "",
      registrationUrl: "https://example.com/crypto-hardware-workshop",
      isFeatured: false,
      approved: true
    },
    {
      id: 3,
      title: "Annual Cryptanalysis Challenge 2024",
      description: "A competitive event where teams work to break various cryptographic systems. This year's focus is on analyzing vulnerabilities in lightweight cryptography solutions for IoT devices. Open to academic teams and security professionals.",
      startDate: "2024-08-05T00:00:00Z",
      endDate: "2024-08-07T23:59:59Z",
      location: "Online",
      imageUrl: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8",
      category: "hackathon",
      source: "college",
      organizerName: "Cryptanalysis Research Group",
      organizerImageUrl: "",
      registrationUrl: "https://example.com/cryptanalysis-challenge",
      isFeatured: true,
      approved: true
    },
    {
      id: 4,
      title: "Introduction to Modern Cryptographic Protocols",
      description: "A comprehensive lecture series covering the fundamentals of modern cryptographic protocols, including TLS 1.3, Signal Protocol, and blockchain consensus mechanisms. Suitable for graduate students and security professionals.",
      startDate: "2024-10-12T14:00:00Z",
      endDate: "2024-10-12T17:00:00Z",
      location: "Boston, MA, USA",
      imageUrl: "https://images.unsplash.com/photo-1513258496099-48168024aec0",
      category: "lecture",
      source: "college",
      organizerName: "Massachusetts Institute of Technology",
      organizerImageUrl: "",
      registrationUrl: "https://example.com/crypto-protocols-lecture",
      isFeatured: false,
      approved: true
    },
    {
      id: 5,
      title: "Cryptography Developers Meetup",
      description: "Monthly gathering of developers working with cryptographic libraries and implementing security solutions. This month's topic: 'Implementing Threshold Signatures for Distributed Systems'.",
      startDate: "2024-06-28T18:00:00Z",
      endDate: "2024-06-28T20:00:00Z",
      location: "San Francisco, CA, USA",
      imageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3",
      category: "meetup",
      source: "college",
      organizerName: "Bay Area Crypto Developers",
      organizerImageUrl: "",
      registrationUrl: "https://example.com/crypto-meetup",
      isFeatured: false,
      approved: true
    },
    {
      id: 6,
      title: "Post-Quantum Cryptography Standardization Panel",
      description: "Industry experts discuss the NIST post-quantum cryptography standardization process and its implications for organizations planning their quantum-safe migration strategies.",
      startDate: "2024-07-05T15:00:00Z",
      endDate: "2024-07-05T17:00:00Z",
      location: "Online",
      imageUrl: "https://images.unsplash.com/photo-1558346490-a72e53ae2d4f",
      category: "webinar",
      source: "college",
      organizerName: "Quantum-Safe Security Alliance",
      organizerImageUrl: "",
      registrationUrl: "https://example.com/pqc-webinar",
      isFeatured: false,
      approved: true
    },
    {
      id: 7,
      title: "Applied Cryptography Certificate Program",
      description: "Comprehensive 6-week program covering all aspects of applied cryptography, from mathematical foundations to practical implementations. Includes hands-on projects and instructor-led sessions.",
      startDate: "2024-09-01T00:00:00Z",
      endDate: "2024-10-15T00:00:00Z",
      location: "Online",
      imageUrl: "https://images.unsplash.com/photo-1605778336817-a05bd4129487",
      category: "workshop",
      source: "college",
      organizerName: "Cybersecurity Education Institute",
      organizerImageUrl: "",
      registrationUrl: "https://example.com/crypto-certificate",
      isFeatured: true,
      approved: true
    },
    {
      id: 8,
      title: "Lightweight Cryptography for IoT Devices",
      description: "A technical workshop focused on implementing efficient cryptographic algorithms on resource-constrained IoT devices. Participants will work with actual hardware to implement and test various solutions.",
      startDate: "2024-11-10T09:00:00Z",
      endDate: "2024-11-11T17:00:00Z",
      location: "Tokyo, Japan",
      imageUrl: "https://images.unsplash.com/photo-1564938470695-161b2df0f329",
      category: "workshop",
      source: "college",
      organizerName: "IoT Security Consortium",
      organizerImageUrl: "",
      registrationUrl: "https://example.com/iot-crypto-workshop",
      isFeatured: false,
      approved: true
    },
    {
      id: 9,
      title: "Zero-Knowledge Proofs Research Symposium",
      description: "Annual symposium for researchers working on zero-knowledge proofs and their applications in privacy-preserving systems, including cryptocurrencies, secure voting, and anonymous credentials.",
      startDate: "2025-01-20T09:00:00Z",
      endDate: "2025-01-22T17:00:00Z",
      location: "Paris, France",
      imageUrl: "https://images.unsplash.com/photo-1523961131990-5ea7c61b2107",
      category: "conference",
      source: "college",
      organizerName: "Privacy Technologies Research Group",
      organizerImageUrl: "",
      registrationUrl: "https://example.com/zkp-symposium",
      isFeatured: false,
      approved: true
    },
    {
      id: 10,
      title: "Cryptography and Blockchain Security Contest",
      description: "Annual competition where participants identify vulnerabilities in blockchain implementations and smart contracts. Cash prizes for teams that find the most significant security issues.",
      startDate: "2024-08-15T00:00:00Z",
      endDate: "2024-08-17T23:59:59Z",
      location: "Virtual Event",
      imageUrl: "https://images.unsplash.com/photo-1639322537228-f710d846310a",
      category: "competition",
      source: "college",
      organizerName: "Blockchain Security Alliance",
      organizerImageUrl: "",
      registrationUrl: "https://example.com/blockchain-security-contest",
      isFeatured: false,
      approved: true
    }
  ];
  
  module.exports = { sampleCryptoEvents };